import { useRef, useState } from 'react';
import { GripVertical, Check, Pencil, Trash2, Search, Plus, Tags, ChevronDown, ChevronRight, RotateCcw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from '@/components/ui/table';
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@/components/ui/collapsible';
import { Checkbox } from '@/components/ui/checkbox';
import { manuallyOrderedTasks, taskKey, reorderIds, settingsFor, setTaskCompleted, isHighlighted, dueTime, type Task } from '../data/planning';
import type { Workspace } from '../platform/workspace';
import type { Change } from './forms';

export function TasksPanel({ workspace, tasks, change, busy, edit, remove, categories }: { workspace: Workspace; tasks: Task[]; change: Change; busy: boolean; edit(task?: Task): void; remove(task: Task): void; categories(): void }) {
  const [open, setOpen] = useState(true), [query, setQuery] = useState(''), [filter, setFilter] = useState('Active');
  const [category, setCategory] = useState(''), [over, setOver] = useState(''), [announcement, setAnnouncement] = useState('');
  const dragged = useRef('');
  const setDragging = (value: string) => { dragged.current = value; };
  const settings = settingsFor(workspace), ordered = manuallyOrderedTasks(tasks, settings);
  const shown = ordered.filter(t => (!category || t.categoryId === category) && (filter === 'All' || (filter === 'Completed' ? t.completed : !t.completed && (filter === 'Active' || t.kind === filter))) && [t.name, t.course, t.category].join(' ').toLowerCase().includes(query.toLowerCase()));
  async function move(from: string, to: string) {
    if (!from || from === to) return;
    const ok = await change(draft => { draft.dashboardSettings = { ...settingsFor(draft), taskOrder: reorderIds(ordered.map(taskKey), from, to) }; });
    if (ok) setAnnouncement('Task order saved.');
    setDragging(''); setOver('');
  }
  return <Card className="panel tasks-panel"><Collapsible open={open} onOpenChange={setOpen}><div className="section-heading"><h2><CollapsibleTrigger asChild><Button variant="ghost" className="heading-toggle">{open ? <ChevronDown /> : <ChevronRight />}Your tasks <Badge variant="secondary">{tasks.length}</Badge></Button></CollapsibleTrigger></h2><div className="toolbar-actions">{!!settings.taskOrder?.length && <Button variant="ghost" size="sm" onClick={() => void change(draft => { draft.dashboardSettings = { ...settingsFor(draft), taskOrder: [] }; })}><RotateCcw />Priority order</Button>}<Button variant="ghost" size="sm" onClick={categories}><Tags />Categories</Button><Button size="sm" onClick={() => edit()}><Plus />Task</Button></div></div><CollapsibleContent id="task-list"><div className="list-toolbar"><div className="filter-tabs">{['Active', 'Assignment', 'To-Do', 'Completed', 'All'].map(x => <Button size="sm" variant="ghost" key={x} aria-pressed={filter === x} onClick={() => setFilter(x)}>{x === 'Assignment' ? 'Assignments' : x === 'To-Do' ? 'To-Dos' : x}</Button>)}</div><select aria-label="Task category" value={category} onChange={e => setCategory(e.target.value)}><option value="">All categories</option>{workspace.academic.options['University/Category'].map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><div className="search-field"><Search size={14} /><Input aria-label="Search tasks" placeholder="Find a task…" value={query} onChange={e => setQuery(e.target.value)} /></div></div>
    <Table className="dense-task-table task-table"><TableHeader><TableRow><TableHead className="grip-cell"><span className="sr-only">Reorder</span></TableHead><TableHead>Task / course</TableHead><TableHead>Priority</TableHead><TableHead>Due date</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{shown.map((task, index) => <TableRow key={taskKey(task)} className={(task.completed ? 'task-completed ' : '') + (over === taskKey(task) ? 'drop-target' : '')} onDragOver={e => { if (dragged.current) { e.preventDefault(); setOver(taskKey(task)); } }} onDrop={e => { e.preventDefault(); if (dragged.current) void move(dragged.current, taskKey(task)); }}><TableCell className="grip-cell"><Button variant="ghost" size="icon-sm" className="drag-grip" draggable={!busy} disabled={busy} aria-label={'Reorder ' + task.name} title="Drag to reorder. Use Alt + Up/Down on this handle." onDragStart={e => { setDragging(taskKey(task)); e.dataTransfer.effectAllowed = 'move'; e.dataTransfer.setData('text/plain', taskKey(task)); }} onDragEnd={() => { setDragging(''); setOver(''); }} onKeyDown={e => { if (e.altKey && ['ArrowUp', 'ArrowDown'].includes(e.key)) { e.preventDefault(); const target = shown[index + (e.key === 'ArrowUp' ? -1 : 1)]; if (target) void move(taskKey(task), taskKey(target)); } }}><GripVertical size={14} /></Button></TableCell><TableCell><div className="task-title"><Checkbox aria-label={(task.completed ? 'Reopen ' : 'Complete ') + task.name} checked={task.completed} disabled={busy} onCheckedChange={value => void change(draft => setTaskCompleted(draft, task, value === true))} /><button className="task-name-button" onClick={() => edit(task)}><span className={isHighlighted(task, settings) ? 'important' : ''}>{task.name}</span><small><i style={{ background: task.color }} />{task.course || task.category || task.kind}<span className="kind-label">{task.kind}</span></small></button></div></TableCell><TableCell><Badge variant="outline" className={'priority-pill priority-' + task.priority.toLowerCase()}>{task.priority}</Badge></TableCell><TableCell className={'due-label ' + (!task.completed && dueTime(task) < Date.now() ? 'text-red' : '')}>{task.due ? new Date(task.due.includes('T') ? task.due : task.due + 'T12:00:00').toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : 'Unscheduled'}</TableCell><TableCell><div className="row-actions justify-end"><Button variant="ghost" size="icon-sm" aria-label={'Edit ' + task.name} onClick={() => edit(task)}><Pencil /></Button><Button variant="ghost" size="icon-sm" aria-label={'Delete ' + task.name} onClick={() => remove(task)}><Trash2 /></Button></div></TableCell></TableRow>)}</TableBody></Table>
    {!shown.length && <div className="empty-small compact-empty"><Check size={16} />{tasks.length ? 'No tasks match these filters.' : 'No tasks yet. Add an assignment or To-Do.'}</div>}
    <div className="task-list-footer"><span>{shown.length} shown · drag handles to arrange · Alt + ↑/↓ for keyboard</span><span>{settings.taskOrder?.length ? 'Manual list order' : 'Priority list order'} · calendar uses your priority rules</span></div></CollapsibleContent>{!open && <p className="collapsed-summary">{tasks.filter(t => !t.completed).length} active tasks</p>}<span className="sr-only" role="status">{announcement}</span></Collapsible></Card>;
}
